# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetURL', models.URLField(max_length=150)),
                ('time', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, default='\u6c5f\u897f\u5409\u5b89', max_length=150)),
                ('go_way', models.CharField(blank=True, default='airplane', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='1999.99', max_digits=12)),
                ('hotel', models.CharField(blank=True, default='\u5982\u5bb6\u8fde\u9501\u9152\u5e97', max_length=100)),
                ('interests', models.CharField(blank=True, default='\u7ea2\u8272\u65c5\u6e38\u3001\u9769\u547d\u6447\u7bee\u3001\u53e4\u9547\u4e61\u6751\u3001\u4eba\u6587\u666f\u89c2', max_length=150)),
                ('data_start', models.CharField(blank=True, default='\u73b0\u5728\u5c31\u8d70', max_length=100)),
                ('data_end', models.CharField(blank=True, default='\u5c31\u5728\u90a3\u91cc\u5b9a\u5c45\u5427', max_length=100)),
                ('comment', models.CharField(blank=True, default='\u6ee1\u5206', max_length=150)),
                ('website', models.CharField(blank=True, default='http://vacations.ctrip.com/grouptravel/p5687321s2.html', max_length=100)),
                ('imageurl', models.CharField(blank=True, default='http://dimg04.c-ctrip.com/images/vacations/images2/1/876/876_70_s28263_C_500_280.jpg', max_length=100)),
            ],
        ),
    ]
